In [1]:
# 여기에 작성하세요
import sqlite3

con = sqlite3.connect(':memory:')
cur = con.cursor()

cur.execute('''
            CREATE TABLE IF NOT EXISTS MENU (
                Item TEXT,
                Category TEXT,
                Serving_Size TEXT,
                Calories INTEGER,
                Total_Fat REAL,
                Sodium REAL,
                Protein REAL
            )
        ''')
con.commit()

# MENU 테이블 생성 (Item, Category, Serving_Size, Calories, Total_Fat, Sodium, Protein)

In [2]:
cur.execute("SELECT name FROM sqlite_master WHERE type='table'")
print(cur.fetchall())
# 결과: [('MENU',)]  -> MENU 테이블이 있으면 성공

[('MENU',)]

In [3]:
import pandas as pd

menu_data = {
    "Item":         ["Big Mac", "McChicken", "McDouble", "Filet-O-Fish",
                     "Quarter Pounder", "McNuggets (10pc)", "Egg McMuffin",
                     "French Fries (M)", "Apple Pie", "Iced Coffee",
                     "Chocolate Shake", "Caesar Salad"],
    "Category":     ["Burgers", "Chicken", "Burgers", "Fish",
                     "Burgers", "Chicken", "Breakfast",
                     "Sides", "Desserts", "Beverages",
                     "Beverages", "Salads"],
    "Serving_Size": ["219g", "164g", "174g", "142g",
                     "198g", "162g", "135g",
                     "117g", "77g", "355mL",
                     "473mL", "225g"],
    "Calories":     [540, 400, 390, 390, 520, 440, 300,
                     340, 250, 140, 530, 90],
    "Total_Fat":    [28.0, 16.0, 19.0, 19.0, 26.0, 27.0, 13.0,
                     16.0, 11.0, 6.0, 13.0, 4.0],
    "Sodium":       [950, 700, 750, 580, 1100, 900, 760,
                     310, 170, 95, 290, 190],
    "Protein":      [25.0, 14.0, 23.0, 15.0, 30.0, 23.0, 17.0,
                     4.0, 2.0, 2.0, 12.0, 7.0]
}


df = pd.DataFrame(menu_data)

con = sqlite3.connect(':memory:')
df.to_sql('MENU', con, if_exists='replace', index=False)

print(f"저장된 행 수 : {len(df)}")

저장된 행 수 : 12

In [4]:
df

,Item,Category,Serving_Size,Calories,Total_Fat,Sodium,Protein
0,Big Mac,Burgers,219g,540,28.0,950,25.0
1,McChicken,Chicken,164g,400,16.0,700,14.0
2,McDouble,Burgers,174g,390,19.0,750,23.0
3,Filet-O-Fish,Fish,142g,390,19.0,580,15.0
4,Quarter Pounder,Burgers,198g,520,26.0,1100,30.0
5,McNuggets (10pc),Chicken,162g,440,27.0,900,23.0
6,Egg McMuffin,Breakfast,135g,300,13.0,760,17.0
7,French Fries (M),Sides,117g,340,16.0,310,4.0
8,Apple Pie,Desserts,77g,250,11.0,170,2.0
9,Iced Coffee,Beverages,355mL,140,6.0,95,2.0
10,Chocolate Shake,Beverages,473mL,530,13.0,290,12.0
11,Caesar Salad,Salads,225g,90,4.0,190,7.0

In [ ]:
cur = con.cursor()
cur.execute("SELECT Item, Category, Calories FROM MENU")

rows = cur.fetchall()

for row in rows:
    print(row)

In [ ]:
cur = con.cursor()
cur.execute("SELECT Item, Category, Calories FROM MENU LIMIT 5")

five = cur.fetchall()

for row in five:
    print(row)

In [ ]:
df_menu = pd.read_sql_query("SELECT * FROM MENU", con)

print(df_menu.head())
print(df_menu.dtypes)

In [10]:
query = """
    SELECT Item, Category, Total_Fat, Protein
    FROM MENU
    Where Category = 'Burgers'
        AND Calories >= 400
"""

df_burgers = pd.read_sql_query(query,con)
print(df_burgers)

              Item Category  Total_Fat  Protein
0          Big Mac  Burgers       28.0     25.0
1  Quarter Pounder  Burgers       26.0     30.0

In [ ]:
df = pd.read_sql_query("SELECT * FROM MENU", con)

# 요약 통계 출력
print(df.describe())

# Q1. Calories 컬럼의 평균은?
avg_cal = df['Calories'].mean()

# Q2. Sodium 컬럼의 최댓값은?
max_sodium = df['Sodium'].max()

# Q3. Protein 컬럼의 최솟값은?
min_protein = df['Protein'].min()

print(f"평균 칼로리: {avg_cal:.1f}")
print(f"최대 나트륨: {max_sodium}")
print(f"최소 단백질: {min_protein}")

In [17]:
# 셀 1: 파일 DB에 데이터 저장
con_file = sqlite3.connect("menu.db")
df.to_sql("MENU", con_file, if_exists="replace", index=False)
con_file.close()

In [ ]:
%reload_ext sql
# 셀 2: SQL Magic 로드 및 연결
%load_ext sql
%sql sqlite:///menu.db

In [22]:
con_file = sqlite3.connect("menu.db")
df.to_sql("MENU", con_file, if_exists="replace", index=False)
con_file.close()

In [33]:
%sql SELECT Item, Category FROM MENU

 * sqlite:///menu.db
Done.

                Item   Category
0            Big Mac    Burgers
1          McChicken    Chicken
2           McDouble    Burgers
3       Filet-O-Fish       Fish
4    Quarter Pounder    Burgers
5   McNuggets (10pc)    Chicken
6       Egg McMuffin  Breakfast
7   French Fries (M)      Sides
8          Apple Pie   Desserts
9        Iced Coffee  Beverages
10   Chocolate Shake  Beverages
11      Caesar Salad     Salads

In [32]:
import prettytable
prettytable.DEFAULT = prettytable.TableStyle.DEFAULT

In [34]:
%sql SELECT Item, Category FROM MENU WHERE Category = 'Beverages'

 * sqlite:///menu.db
Done.

              Item   Category
0      Iced Coffee  Beverages
1  Chocolate Shake  Beverages

In [36]:
%%sql
SELECT Category,
    COUNT(*) As item_count,
    AVG(Calories) AS avg_calories
FROM MENU

 * sqlite:///menu.db
Done.

  Category  item_count  avg_calories
0  Burgers          12    360.833333

In [38]:
%sql SELECT * FROM MENU

 * sqlite:///menu.db
Done.

,Item,Category,Serving_Size,Calories,Total_Fat,Sodium,Protein
0,Big Mac,Burgers,219g,540,28.0,950,25.0
1,McChicken,Chicken,164g,400,16.0,700,14.0
2,McDouble,Burgers,174g,390,19.0,750,23.0
3,Filet-O-Fish,Fish,142g,390,19.0,580,15.0
4,Quarter Pounder,Burgers,198g,520,26.0,1100,30.0
5,McNuggets (10pc),Chicken,162g,440,27.0,900,23.0
6,Egg McMuffin,Breakfast,135g,300,13.0,760,17.0
7,French Fries (M),Sides,117g,340,16.0,310,4.0
8,Apple Pie,Desserts,77g,250,11.0,170,2.0
9,Iced Coffee,Beverages,355mL,140,6.0,95,2.0
10,Chocolate Shake,Beverages,473mL,530,13.0,290,12.0
11,Caesar Salad,Salads,225g,90,4.0,190,7.0

In [39]:
# 방법 1: SQL 서브쿼리
query_sql = """
    SELECT *
    FROM MENU
    WHERE Sodium = (SELECT MAX(Sodium) FROM MENU)
"""
df_max = pd.read_sql_query(query_sql, con)
print(df_max)

              Item Category Serving_Size  Calories  Total_Fat  Sodium  Protein
0  Quarter Pounder  Burgers         198g       520       26.0    1100     30.0

In [40]:
%sql SELECT MAX(Sodium) FROM MENU

 * sqlite:///menu.db
Done.

   MAX(Sodium)
0         1100

In [41]:
df = pd.read_sql_query("SELECT * FROM MENU", con)
max_row = df.loc[df['Sodium'].idxmax()]
print(max_row[['Item', 'Category', 'Sodium']])

Item        Quarter Pounder
Category            Burgers
Sodium                 1100
Name: 4, dtype: object

In [45]:
import sqlite3
import pandas as pd

# 1. 데이터 저장
menu_data = {
    "Item":         ["Big Mac", "McChicken", "McDouble", "Filet-O-Fish",
                     "Quarter Pounder", "McNuggets (10pc)", "Egg McMuffin",
                     "French Fries (M)", "Apple Pie", "Iced Coffee",
                     "Chocolate Shake", "Caesar Salad"],
    "Category":     ["Burgers", "Chicken", "Burgers", "Fish",
                     "Burgers", "Chicken", "Breakfast",
                     "Sides", "Desserts", "Beverages",
                     "Beverages", "Salads"],
    "Serving_Size": ["219g", "164g", "174g", "142g",
                     "198g", "162g", "135g",
                     "117g", "77g", "355mL",
                     "473mL", "225g"],
    "Calories":     [540, 400, 390, 390, 520, 440, 300,
                     340, 250, 140, 530, 90],
    "Total_Fat":    [28.0, 16.0, 19.0, 19.0, 26.0, 27.0, 13.0,
                     16.0, 11.0, 6.0, 13.0, 4.0],
    "Sodium":       [950, 700, 750, 580, 1100, 900, 760,
                     310, 170, 95, 290, 190],
    "Protein":      [25.0, 14.0, 23.0, 15.0, 30.0, 23.0, 17.0,
                     4.0, 2.0, 2.0, 12.0, 7.0]
}

con = sqlite3.connect(":memory:")
df_raw = pd.DataFrame(menu_data)
df_raw.to_sql("MENU",con, if_exists="replace", index=False)

# 2. SQL 집계 쿼리 작성
query = """
    SELECT
        Category,
        COUNT(*),
        ROUND(AVG(Calories),1) AS avg_calories,
        MAX(Protein)
    FROM MENU
    GROUP BY Category
    ORDER BY avg_calories DESC
"""

# 3. DataFrame으로 읽기
df_summary = pd.read_sql_query(query,con)

# 4. 출력
print("=== 카테고리별 영양 정보 요약 ===")
print(df_summary.to_string(index=False))

con.close()

=== 카테고리별 영양 정보 요약 ===
 Category  COUNT(*)  avg_calories  MAX(Protein)
  Burgers         3         483.3          30.0
  Chicken         2         420.0          23.0
     Fish         1         390.0          15.0
    Sides         1         340.0           4.0
Beverages         2         335.0          12.0
Breakfast         1         300.0          17.0
 Desserts         1         250.0           2.0
   Salads         1          90.0           7.0